### ISSUE TITLE
IDEA suggests GMaven import, even though project is GMaven already

### ISSUE THREAD

**Issue by kriegaex** [grisha9/gmaven-plugin#14]
Since the latest upgrade to 233.28, I see IDEA suggest this each time I reopen the same GMaven project:

![image](https://github.com/grisha9/gmaven-plugin/assets/1537384/09260cd1-d0bf-4a5d-bd1d-cb002f6801c5)

**Comment by grisha9** [comment]
I think it is similar https://github.com/grisha9/gmaven-plugin/issues/12
I cant reproduced it to locally, but I think that this is also due to your environment, that you have two users. And apparently an event arrives from the file system where the path contains another user name. Not the one under which the project is registered with IDEA. 
I'll try to fix this, but of course it will be difficult to do in my environment. It is difficult to guarantee 100% results.

**Comment by kriegaex** [comment]
On Linux, it should be possible to recreate the situation with a soft link like `/home/grigoriy` → `/home/grisha` or vice versa, if you think that is (part of) the problem.

**Comment by grisha9** [comment]
I tried to fix it in [233.28.1](https://plugins.jetbrains.com/plugin/22370-gmaven/edit/versions/beta)
But I'm not sure that this can help. If a project is registered in one path, but an event comes from the idea virtual file system with a different path, then a problem occurs. 
I made a cast to the canonical path.
