### ISSUE TITLE
Project import does not up-/downgrade dependency versions

### ISSUE THREAD

**Issue by kriegaex** [grisha9/gmaven-plugin#8]
In my Tycho project, I lately changed a dependency version. Then GMaven reimported everything, but in IDEA the dependency version remained unchanged. I had to manually remove the library in the project settings and reimport one more time to get a correct version.

**Comment by grisha9** [comment]
This is very strange because it is a simple data mapping from maven. And I not reproduce it.
I tested it on my simple project for testing tycho https://github.com/grisha9/eclipse-tycho  

https://github.com/grisha9/gmaven-plugin/assets/8025831/d51545ee-8564-43d0-adc0-a7aee6787c49   

I think the problem is that you are opening the same project with two plugins at once: gmaven and bundled maven. 
I don't recommend doing this. Because bundled maven uses a flatter project structure and it can override the gmaven project structure. 
GMaven:
![image](https://github.com/grisha9/gmaven-plugin/assets/8025831/a91407b9-625f-4d7e-be59-fa9d6800b214)  

Bundled Maven:   
![image](https://github.com/grisha9/gmaven-plugin/assets/8025831/62f3b4c2-cea0-4a38-b40c-e1fd40663a2f)

**Comment by kriegaex** [comment]
No, in my AJDT project I have unlinked the Maven project a few weeks ago, I use GMaven exclusively for that project. Only in other project, I use the normal Maven integration. IDEA suggests to add the project as normal Maven too, but I always ignore that, exactly to avoid double imports.

**Comment by grisha9** [comment]
Can you write more exact reproduction steps? What and where dependency was changed?
I understand that we are talking about the project https://github.com/eclipse-aspectj/ajdt

**Comment by kriegaex** [comment]
Yes, we are talking about that projet. I was on branch _e431_, using profiles _e431_ and _intellij_. The latter imports `aspectjtools`. I changed the dependency version in the root POM and reimported the project. Afterwards, the old version was still listed in the libraries section of the IDEA project.

**Comment by grisha9** [comment]
> Yes, we are talking about that projet. I was on branch _e431_, using profiles _e431_ and _intellij_. The latter imports `aspectjtools`. I changed the dependency version in the root POM and reimported the project. Afterwards, the old version was still listed in the libraries section of the IDEA project.

Sorry, but I can't reproduce it. I changed version from 1.9.22 to 1.9.21.
First import was fail (if run import command  from the command line manually there will also be an error after changing the version). If import is fail then project data(and libraries too) not updated. After second import attempt version was changed to 1.9.21 successfully.   

https://github.com/grisha9/gmaven-plugin/assets/8025831/ac70b155-6611-40bd-af2a-3790dd299eb9

**Comment by grisha9** [comment]
Sorry, but I can't reproduce it. See comment https://github.com/grisha9/gmaven-plugin/issues/8#issuecomment-2083345544
